name: xkcd-viewer
port: 8000
description: View XKCD comics

replicas:
  min: 1
  max: 1

package:
  src_paths:
    - ./src

dependencies:
  pypi:
    streamlit: ""

commands:
  - streamlit run deployments/xkcd-viewer/app.py --server.port 8000
